// Auto-generated by inject_version_define.py - DO NOT EDIT
// Source: library.json

#ifndef AUDIO_VERSION_AUTOGEN_H
#define AUDIO_VERSION_AUTOGEN_H

#define WEB_MODULE_VERSION_STR "0.0.0"
#define WEB_MODULE_VERSION "0.0.0"

#endif // AUDIO_VERSION_AUTOGEN_H
